#!/bin/bash

clear
set -e
tabs -2

TEST_TIMEOUT="2s"
BUILD_FLAGS=""
#BUILD_FLAGS=-gcflags -m -ldflags "-s -w"

printUsage() {
	println "Usage:"
	println "\t" "./godo [help]" "\t\t" "# Print usage"
	println "\t" "./godo clean " "\t\t" "# Clean Go caches"
	println "\t" "./godo test  " "\t\t" "# fmt -> test -> vet"
	println "\t" "./godo run   " "\t\t" "# run"
	println "\t" "./godo commit" "\t\t" "# fmt -> test -> vet"
}

println() {
	for s in "$@"
	do
		printf "$s"
	done
	printf "\\n"
}

goClean() {
	println "Deep cleaning..."
	go clean -cache -testcache
}

goFmt() {
	println "Formatting..."
	go fmt ./...
}

goRun() {
	println "Running..."
	go run .
}

goTest() {
	println "Testing..."
	go test ./... -timeout $TEST_TIMEOUT
}

goVet() {
	println "Vetting..."
	go vet ./...
}

if [[ "$1" == "" || "$1" == "help" ]]; then
	printUsage
	exit 0
fi

if [[ "$1" == "docs" ]]; then
	goDoc
	exit 0
fi

if [[ "$1" == "clean" ]]; then
	goClean
	exit 0
fi

if [[ "$1" == "run" ]]; then
	goRun
	exit 0
fi

if [[ "$1" == "test" || "$1" == "commit" ]]; then
	goFmt
	goTest
	goVet
	exit 0
fi

println "I don't understand the option '$1'."
printUsage
exit 1
